/*
 * This source file was generated by the Gradle 'init' task
 */
package ifsc.poo.login;

import java.lang.reflect.GenericArrayType;

public class App {
    public static void main(String[] args) {
        Gerenciador.cadastraUsuario("A", "123");
        Gerenciador.cadastraUsuario("B", "456");
        Gerenciador.cadastraUsuario("C", "789");
        Gerenciador.listaUsuarios();
        System.out.println(Gerenciador.getQtd_usuarios());

        Gerenciador.removeUsuario("B");
        Gerenciador.listaUsuarios();
        System.out.println(Gerenciador.getQtd_usuarios());

        System.out.println("O usuário B com senha 456 é válido? " + Gerenciador.autenticaUsuario("B", "456"));
        System.out.println("O usuário D com senha 456 é válido? " + Gerenciador.autenticaUsuario("D", "456"));
        System.out.println("O usuário C com senha 123 é válido? " + Gerenciador.autenticaUsuario("C", "123"));
        System.out.println("O usuário A com senha 123 é válido? " + Gerenciador.autenticaUsuario("A", "123"));
        System.out.println("O usuário C com senha 789 é válido? " + Gerenciador.autenticaUsuario("C", "789"));
    }
}
